server:
  port: 8080

spring:
  activemq:
    broker-url: tcp://10.10.10.103:61616
    user: admin
    password: admin
  jms:
    # pub-sub-domain: false # false: Queue true: Topic
    pub-sub-domain: true # false: Queue true: Topic

# 自定义队列名称
deemo:
  queue: boot-deemo-queue
  topic: boot-deemo-topic
